namespace: default

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 3

pagerbotAdmin:
  name: pagerbot-admin
  replicas: 0

pagerbot:
  name: pagerbot

image:
  repository: quay.io/lunarway/pagerbot
  tag: 0.0.1
